services:
  - type: web
    name: brandtopup-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_sqlite:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.vercel.app 